version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: sadmin
      POSTGRES_PASSWORD: 123
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
